#!/bin/bash

unity_dll=/Applications/Unity/Unity.app/Contents/Frameworks/Managed/UnityEngine.dll
docs_xml=Docs/xml
docs_html=Docs/monohtml
template=Docs/template.xsl

target_xml=$(echo "$1" | awk {sub\(/\\.dll\$/\,\".xml\"\,\$0\)\;print})

mdoc update --delete -i "$target_dir/$target_xml" -r="$unity_dll" -o "$docs_xml" "$1"
mdoc export-html --template "$template" -o "$docs_html" "$docs_xml"
